# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-02-11 13:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='dummy',
            field=models.BooleanField(default=False),
        ),
    ]
