# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-28 09:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0005_auto_20190828_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('SCHA', 'School Admin'), ('SCHT', 'School Teacher'), ('RO', 'Read Only')], default='A', max_length=45),
        ),
    ]
