# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-16 08:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0006_auto_20190828_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('NS', 'Not Set')], default='NS', max_length=5),
        ),
    ]
