# Generated by Django 3.1.4 on 2022-04-05 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0010_auto_20211109_1005'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='filter_args',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
