# Generated by Django 3.1.4 on 2022-04-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0011_myuser_filter_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='role',
            field=models.CharField(choices=[('A', 'Admin'), ('SCHA', 'School Admin'), ('SCHT', 'School Teacher'), ('CO', 'County Officer'), ('SCO', 'Sub County Officer'), ('RO', 'Read Only')], default='A', max_length=45),
        ),
    ]
