# Generated by Django 3.1.4 on 2023-09-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0012_auto_20220405_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_partner',
            field=models.BooleanField(default=False),
        ),
    ]
