version: "3.8"
services:
  
  media:
    image: nginx:1.15
    networks:
      - db
    ports:
      - 8888:80

    volumes:
      - media:/usr/share/nginx/media
      - static:/usr/share/nginx/static
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      
  api:
    image: michameiu/daa-v2-api:v1.0.1 # Location with a Dockerfile
    restart: always
    depends_on:
      - db
      - memcached
    networks:
      - db

    environment:
      SECRET_KEY: p9878787629839823
      DB_PASSWORD: VKMCrEDlMGYjSe3
      DB_USER: moeke
      DB_NAME: moekeapi 
      DB_HOST: db

    ports:
      - 8020:8000
  
  background_tasks:
    image: michameiu/daa-v2-api:v1.0.1 # Location with a Dockerfile
    restart: always
    command: python manage.py process_tasks

    depends_on:
      - db
      - memcached
    
    networks:
      - db

    environment:
      SECRET_KEY: p9878787629839823
      DB_PASSWORD: VKMCrEDlMGYjSe3
      DB_USER: moeke
      DB_NAME: moekeapi 
      DB_HOST: db

  
  memcached:
    image: memcached:latest
    ports:
      - "11211:11211"
    
    networks:
      - db


  db:
    image: postgres
    restart: always
    networks:
      - db
    environment:
      POSTGRES_PASSWORD: VKMCrEDlMGYjSe3
      POSTGRES_USER: moeke
      POSTGRES_DB: moekeapi
    volumes:
      - pg:/var/lib/postgresql/data
    ports:
      - 3001:3000
    
    
networks:
  db:

volumes:
  pg: