# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-20 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20190720_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(default='last_name', max_length=45),
            preserve_default=False,
        ),
    ]
