# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-20 15:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_teacher_is_school_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='non_delete',
            new_name='is_non_delete',
        ),
    ]
