# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-21 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_auto_20190720_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together=set([('school', 'name')]),
        ),
    ]
