# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_auto_20190721_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='stay_with',
        ),
        migrations.AddField(
            model_name='student',
            name='guardian_status',
            field=models.CharField(choices=[('B', 'Both Parents'), ('S', 'Single Parent'), ('N', 'None'), ('NS', 'Not Set')], default='NS', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='special_needs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('N', 'None'), ('V', 'Visual'), ('H', 'Hearing'), ('P', 'Physical'), ('L', 'Learning')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('N', 'None'), ('R', 'Refugee'), ('A', 'Asylum'), ('I', 'Idp'), ('NS', 'Not Set')], default='NS', max_length=5),
        ),
    ]
