# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-23 15:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_auto_20190722_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeleteReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45, unique=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='StudentDeleteReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, max_length=1500, null=True)),
                ('reason', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.DeleteReason')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
