# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-26 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_deletereason_studentdeletereason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE')], default='M', max_length=2),
        ),
    ]
