# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-30 09:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20190726_1313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stream',
            name='name',
            field=models.CharField(default='', max_length=45),
        ),
        migrations.AlterUniqueTogether(
            name='stream',
            unique_together=set([]),
        ),
    ]
