# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 13:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_auto_20190730_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='GraduatesStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('year', models.PositiveSmallIntegerField(max_length=4)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='graduate_streams', to='school.School')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='graduates_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.GraduatesStream'),
        ),
        migrations.AlterUniqueTogether(
            name='graduatesstream',
            unique_together=set([('school', 'year')]),
        ),
    ]
