# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-04 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20190801_1609'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromoteSchool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('year', models.PositiveSmallIntegerField(max_length=4)),
                ('graduates_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='school.GraduatesStream')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.School')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PromoteStream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('completed', models.BooleanField(default=False)),
                ('next_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_class', to='school.Stream')),
                ('prev_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prev_class', to='school.Stream')),
                ('promote_school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stream_promotions', to='school.PromoteSchool')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('next_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='next_class', to='school.Stream')),
                ('prev_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='previous_class', to='school.Stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
