# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-07 15:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_promoteschool_promotestream_promotions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotions',
            name='next_class',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='prev_class',
        ),
        migrations.RemoveField(
            model_name='promotions',
            name='student',
        ),
        migrations.DeleteModel(
            name='Promotions',
        ),
    ]
