# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-07 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20190807_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoteschool',
            name='graduates_class',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.GraduatesStream'),
        ),
    ]
