# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-13 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_absentreason_studentabsentreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentabsentreason',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
