# Generated by Django 3.1.4 on 2021-07-15 07:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0021_auto_20190916_0403'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotestream',
            name='next_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='next_class', to='school.stream'),
        ),
        migrations.AlterField(
            model_name='promotestream',
            name='prev_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='prev_class', to='school.stream'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher', to=settings.AUTH_USER_MODEL),
        ),
    ]
