# Generated by Django 3.1.4 on 2021-07-16 08:57
from django.contrib.postgres.fields import JSONField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20210715_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='moe_extra_info',
            field=JSONField(blank=True, editable=False, null=True),
        ),
    ]
