# Generated by Django 3.1.4 on 2021-07-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_student_moe_extra_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='moe_unique_id',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
