# Generated by Django 3.1.4 on 2021-07-23 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0026_stream_moe_section_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='temp_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
