# Generated by Django 3.1.4 on 2021-07-23 14:51
from django.contrib.postgres.fields import JSONField
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_student_temp_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='moe_extra_info',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
