# Generated by Django 3.1.4 on 2021-08-08 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0028_auto_20210723_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='distance_from_school',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
