# Generated by Django 3.1.4 on 2021-08-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0029_student_distance_from_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='moe_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
