# Generated by Django 3.1.4 on 2021-08-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_stream_moe_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='stream',
            name='moe_section_name',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
