# Generated by Django 3.0.8 on 2021-11-09 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0032_auto_20211109_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='upi',
            field=models.CharField(blank=True, help_text='Unique Identification provided by the school', max_length=45, null=True),
        ),
    ]
