# Generated by Django 3.1.4 on 2021-11-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_student_upi'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='tsc_no',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='type',
            field=models.CharField(choices=[('TSC', 'TSC'), ('BRD', 'BOARD')], default='TSC', max_length=3),
        ),
    ]
