# Generated by Django 3.1.4 on 2021-11-09 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0034_auto_20211109_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='marital_status',
            field=models.CharField(choices=[('NS', 'Not Set'), ('S', 'Single'), ('M', 'Married'), ('D', 'Divorced')], default='NS', max_length=3),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='qualifications',
            field=models.CharField(blank=True, choices=[('NS', 'Not Set'), ('UNI', 'UNIVERSITY'), ('COL', 'COLLEGE')], default='NS', max_length=3, null=True),
        ),
    ]
