# Generated by Django 3.1.4 on 2021-11-10 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_specialneed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='special_needs',
        ),
    ]
