# Generated by Django 3.1.4 on 2021-11-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0037_remove_student_special_needs'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='special_needs',
            field=models.ManyToManyField(blank=True, null=True, related_name='students', to='school.SpecialNeed'),
        ),
    ]
