# Generated by Django 3.1.4 on 2021-11-18 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_student_special_needs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('first_name', 'id')},
        ),
    ]
