# Generated by Django 3.1.4 on 2021-11-18 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_county_subcounty'),
        ('school', '0039_auto_20211118_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='region.subcounty'),
        ),
        migrations.AddField(
            model_name='student',
            name='village',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
