# Generated by Django 3.1.4 on 2021-11-18 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_county_subcounty'),
        ('school', '0040_auto_20211118_1346'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guardian_sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_guardians', to='region.subcounty'),
        ),
    ]
