# Generated by Django 3.1.4 on 2021-11-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_student_guardian_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('MX', 'Mixed')], default='MX', max_length=4),
        ),
        migrations.AlterField(
            model_name='school',
            name='schooling',
            field=models.CharField(choices=[('D', 'Day Only'), ('B', 'Boarding Only'), ('BD', 'Boarding and Day')], default='D', max_length=4),
        ),
    ]
