# Generated by Django 3.1.4 on 2021-11-18 20:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_county_subcounty'),
        ('school', '0043_auto_20211118_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school',
            name='village',
        ),
        migrations.AddField(
            model_name='school',
            name='sub_county',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='schools', to='region.subcounty'),
        ),
    ]
