# Generated by Django 3.1.4 on 2021-11-20 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0044_auto_20211118_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='highest_grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='P8', max_length=4),
        ),
        migrations.AlterField(
            model_name='school',
            name='lowest_grade',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8')], default='P1', max_length=4),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='date_started_teaching',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='dob',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='joined_current_school',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
