# Generated by Django 3.1.4 on 2021-11-22 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_auto_20211120_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='date_started_teaching',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='joined_current_school',
            field=models.DateField(blank=True, null=True),
        ),
    ]
