# Generated by Django 3.1.4 on 2021-11-23 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0047_auto_20211122_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('NS', 'Not Set'), ('OOSC', 'Out Of School'), ('NWE', 'Newly Enrolled'), ('NVE', 'Never Enrolled'), ('PE', 'Previously Enrolled')], default='NS', max_length=5),
        ),
    ]
