# Generated by Django 3.1.4 on 2022-02-22 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_student_knows_dob'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['gender'], name='students_gender_indx'),
        ),
    ]
