# Generated by Django 3.1.4 on 2022-02-22 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0051_auto_20220222_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ('id',)},
        ),
    ]
