# Generated by Django 3.1.4 on 2022-04-04 04:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0052_auto_20220222_1844'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolsStudentsImport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=45, null=True)),
                ('import_file', models.FileField(upload_to='imports')),
                ('step', models.CharField(choices=[('Q', 'Queued'), ('VH', 'Validating Required Columns'), ('PI', 'Preparing import'), ('I', 'Importing'), ('F', 'Failed'), ('D', 'Done')], default='Q', max_length=3)),
                ('errors_file', models.FileField(blank=True, null=True, upload_to='imports')),
                ('start_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('end_time', models.DateTimeField(blank=True, editable=False, null=True)),
                ('args', models.TextField(blank=True, editable=False, max_length=1000, null=True)),
                ('rows_count', models.IntegerField(default=0, editable=False)),
                ('imported_rows_count', models.IntegerField(default=0, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
                'abstract': False,
            },
        ),
    ]
