# Generated by Django 3.1.4 on 2022-04-04 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0053_schoolsstudentsimport'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsstudentsimport',
            name='errors',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
    ]
