# Generated by Django 3.1.4 on 2022-04-04 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_schoolsstudentsimport_errors'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsstudentsimport',
            name='duplicates_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
