# Generated by Django 3.1.4 on 2022-04-04 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_schoolsstudentsimport_duplicates_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsstudentsimport',
            name='new_students_created',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='schoolsstudentsimport',
            name='step',
            field=models.CharField(choices=[('Q', 'Queued'), ('VH', 'Validating Required Columns'), ('PI', 'Preparing import'), ('I', 'Importing'), ('F', 'Failed'), ('D', 'Done')], default='Q', editable=False, max_length=3),
        ),
    ]
