# Generated by Django 3.1.4 on 2022-04-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0056_auto_20220404_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('OOSC', 'Out of School'), ('NE', 'Newly Enrolled'), ('PE', 'Previously Enrolled')], max_length=5),
        ),
    ]
