# Generated by Django 3.1.4 on 2022-04-05 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0057_auto_20220404_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('OOSC', 'Out of School'), ('NE', 'Newly Enrolled'), ('PE', 'Previously Enrolled')], default='NE', max_length=5),
        ),
    ]
