# Generated by Django 3.1.4 on 2022-04-06 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0058_auto_20220405_0611'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsstudentsimport',
            name='error_rows_count',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
