# Generated by Django 3.1.4 on 2022-04-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0062_auto_20220407_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsstudentsimport',
            name='errors',
            field=models.TextField(default='', max_length=2000),
        ),
    ]
