# Generated by Django 3.1.4 on 2022-07-20 09:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0064_update_school_creds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='gender',
            field=models.CharField(choices=[('M', 'Boys'), ('F', 'Girls'), ('MX', 'Mixed')], default='MX', max_length=4),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='client.myuser'),
            preserve_default=False,
        ),
    ]
