# Generated by Django 3.1.4 on 2022-10-14 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0066_auto_20220720_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolsstudentsimport',
            name='import_type',
            field=models.CharField(choices=[('F', 'Import File'), ('NC', 'Nemis County'), ('NSC', 'Nemis Sub County'), ('NSCH', 'Nemis School'), ('JSON', 'Json Data')], default='F', max_length=5),
        ),
        migrations.AddField(
            model_name='schoolsstudentsimport',
            name='nemis_group_id',
            field=models.CharField(blank=True, help_text='The County Id, Sub county Id, School Id', max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='schoolsstudentsimport',
            name='nemis_institution_level',
            field=models.CharField(blank=True, help_text='Nemis Institution Level', max_length=45, null=True),
        ),
    ]
