# Generated by Django 3.1.4 on 2022-10-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0068_auto_20221014_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolsstudentsimport',
            name='import_file',
            field=models.FileField(blank=True, null=True, upload_to='imports'),
        ),
    ]
