# Generated by Django 3.1.4 on 2023-01-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0072_auto_20230117_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='is_training_school',
            field=models.BooleanField(default=False),
        ),
    ]
