# Generated by Django 3.1.4 on 2023-06-09 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0075_schoolsstudentsimport_update_learner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='emis_code',
            field=models.CharField(max_length=45),
        ),
    ]
