# Generated by Django 3.1.4 on 2023-06-09 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0076_auto_20230609_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='emis_code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=45),
        ),
    ]
