version: "3"
services:
  registry:
    image: registry
    networks:
      - ovencrypt

    volumes:
      - registry:/var/lib/registry


    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.registry.rule=Host(`registry.onekana.ke`)" 
        - "traefik.http.services.registry.loadbalancer.server.port=5000"
        - "traefik.docker.network=ovencrypt"

      placement:
        constraints: 
          - node.hostname == swarm-leader
    

networks:
  ovencrypt:
    external: true
    attachable: true

volumes:
  registry: 