# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-13 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='village',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='village',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
