# Generated by Django 3.1.4 on 2023-10-03 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0003_county_subcounty'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcounty',
            name='partner_names',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
