version: "3.9"

services:
  api:
    image: dockerhubusername/moekeapi

    networks:
      - ovencrypt

    deploy:
      replicas: 2
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.api.rule=Host(`api.onekana.ke`)"
        - "traefik.http.services.api.loadbalancer.server.port=8000"
        - "traefik.docker.network=ovencrypt"

networks:
  ovencrypt:
    external: true
    attachable: true
