#!/bin/bash

SCTRIPTS_FOLDER=$(dirname "${0}")
set -e
cd "$(dirname "$0")"
pwd
./pipinstall
#./django_test
./migrate
./collectstatic

# cd $SCTRIPTS_FOLDER/../
# /home/requestafricadev/.local/bin/supervisorctl  -c /home/requestafricadev/apps/moekeapi/process_tasks.conf <<EOF restart myapp
# EOF


touch /home/requestafricadev/apps/moekeapi/moekeapi/wvapi/wsgi.py || true

#sudo /home/daa/apps/api/updateScript.sh
