# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-13 09:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_question', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supportquestion',
            name='description',
            field=models.TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='supportquestion',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
