# Generated by Django 3.1.4 on 2021-12-14 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_question', '0003_supportrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportrequest',
            name='subject',
            field=models.CharField(default='', max_length=900),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='supportrequest',
            name='body',
            field=models.TextField(max_length=3000),
        ),
    ]
