# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('school', '0008_auto_20190722_1403'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.CharField(max_length=70, primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('status', models.IntegerField(choices=[(1, 'Present'), (0, 'Absent')], default=0)),
                ('cause_of_absence', models.CharField(blank=True, max_length=200, null=True)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Stream')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Student')),
            ],
            options={
                'ordering': ('id',),
                'get_latest_by': 'date',
            },
        ),
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('date', models.DateField()),
                ('id', models.CharField(blank=True, max_length=50, primary_key=True, serialize=False)),
                ('present', models.IntegerField(default=0)),
                ('absent', models.IntegerField(default=0)),
                ('stream', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='school.Stream')),
            ],
        ),
    ]
