# Generated by Django 3.1.4 on 2021-08-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_auto_20210803_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherattendance',
            name='is_present',
        ),
        migrations.AddField(
            model_name='teacherattendance',
            name='status',
            field=models.IntegerField(choices=[(1, 'Present'), (0, 'Absent')], default=0),
        ),
    ]
